# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NotePad.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 534)
        MainWindow.setStyleSheet("background-color: rgb(35, 37, 46);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.slideMenu_container = QtWidgets.QFrame(self.centralwidget)
        self.slideMenu_container.setMaximumSize(QtCore.QSize(0, 16777215))
        self.slideMenu_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.slideMenu_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.slideMenu_container.setObjectName("slideMenu_container")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.slideMenu_container)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.SliderMenu_3 = QtWidgets.QFrame(self.slideMenu_container)
        self.SliderMenu_3.setMinimumSize(QtCore.QSize(198, 0))
        self.SliderMenu_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SliderMenu_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SliderMenu_3.setObjectName("SliderMenu_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.SliderMenu_3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_20 = QtWidgets.QFrame(self.SliderMenu_3)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.Welcome_3 = QtWidgets.QFrame(self.frame_20)
        self.Welcome_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Welcome_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Welcome_3.setObjectName("Welcome_3")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.Welcome_3)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_13 = QtWidgets.QLabel(self.Welcome_3)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_34.addWidget(self.label_13)
        self.horizontalLayout_33.addWidget(self.Welcome_3, 0, QtCore.Qt.AlignTop)
        self.Top_4 = QtWidgets.QFrame(self.frame_20)
        self.Top_4.setStyleSheet("border:url(:/icon2/icons_1/smile.svg);")
        self.Top_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Top_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_4.setObjectName("Top_4")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.Top_4)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_14 = QtWidgets.QLabel(self.Top_4)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_35.addWidget(self.label_14)
        self.horizontalLayout_33.addWidget(self.Top_4, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_13.addWidget(self.frame_20, 0, QtCore.Qt.AlignTop)
        self.frame_21 = QtWidgets.QFrame(self.SliderMenu_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_21.sizePolicy().hasHeightForWidth())
        self.frame_21.setSizePolicy(sizePolicy)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.Main_toolBox_3 = QtWidgets.QToolBox(self.frame_21)
        self.Main_toolBox_3.setObjectName("Main_toolBox_3")
        self.Home_3 = QtWidgets.QWidget()
        self.Home_3.setGeometry(QtCore.QRect(0, 0, 158, 225))
        self.Home_3.setObjectName("Home_3")
        self.Main_toolBox_3.addItem(self.Home_3, "")
        self.Class_3 = QtWidgets.QWidget()
        self.Class_3.setGeometry(QtCore.QRect(0, 0, 150, 342))
        self.Class_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Class_3.setObjectName("Class_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.Class_3)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.Btn_class_3 = QtWidgets.QPushButton(self.Class_3)
        self.Btn_class_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Btn_class_3.setObjectName("Btn_class_3")
        self.verticalLayout_15.addWidget(self.Btn_class_3)
        self.Btn_meet_3 = QtWidgets.QPushButton(self.Class_3)
        self.Btn_meet_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Btn_meet_3.setObjectName("Btn_meet_3")
        self.verticalLayout_15.addWidget(self.Btn_meet_3)
        self.Btn_test_3 = QtWidgets.QPushButton(self.Class_3)
        self.Btn_test_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Btn_test_3.setObjectName("Btn_test_3")
        self.verticalLayout_15.addWidget(self.Btn_test_3)
        self.Btn_trans_3 = QtWidgets.QPushButton(self.Class_3)
        self.Btn_trans_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Btn_trans_3.setObjectName("Btn_trans_3")
        self.verticalLayout_15.addWidget(self.Btn_trans_3)
        self.Btn_players_3 = QtWidgets.QPushButton(self.Class_3)
        self.Btn_players_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Btn_players_3.setObjectName("Btn_players_3")
        self.verticalLayout_15.addWidget(self.Btn_players_3)
        self.Btn_Board_3 = QtWidgets.QPushButton(self.Class_3)
        self.Btn_Board_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Btn_Board_3.setObjectName("Btn_Board_3")
        self.verticalLayout_15.addWidget(self.Btn_Board_3)
        self.Btn_notepad_3 = QtWidgets.QPushButton(self.Class_3)
        self.Btn_notepad_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Btn_notepad_3.setObjectName("Btn_notepad_3")
        self.verticalLayout_15.addWidget(self.Btn_notepad_3)
        self.Btn_timeTable_3 = QtWidgets.QPushButton(self.Class_3)
        self.Btn_timeTable_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Btn_timeTable_3.setObjectName("Btn_timeTable_3")
        self.verticalLayout_15.addWidget(self.Btn_timeTable_3)
        self.Btn_SocialMidea_3 = QtWidgets.QPushButton(self.Class_3)
        self.Btn_SocialMidea_3.setFocusPolicy(QtCore.Qt.TabFocus)
        self.Btn_SocialMidea_3.setObjectName("Btn_SocialMidea_3")
        self.verticalLayout_15.addWidget(self.Btn_SocialMidea_3)
        self.Btn_Others_3 = QtWidgets.QPushButton(self.Class_3)
        self.Btn_Others_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Btn_Others_3.setObjectName("Btn_Others_3")
        self.verticalLayout_15.addWidget(self.Btn_Others_3)
        self.Main_toolBox_3.addItem(self.Class_3, "")
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setGeometry(QtCore.QRect(0, 0, 158, 225))
        self.page_7.setObjectName("page_7")
        self.Main_toolBox_3.addItem(self.page_7, "")
        self.verticalLayout_14.addWidget(self.Main_toolBox_3)
        self.verticalLayout_13.addWidget(self.frame_21)
        self.last_frame_3 = QtWidgets.QFrame(self.SliderMenu_3)
        self.last_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.last_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.last_frame_3.setObjectName("last_frame_3")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.last_frame_3)
        self.horizontalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_36.setSpacing(0)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.l1_3 = QtWidgets.QFrame(self.last_frame_3)
        self.l1_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.l1_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.l1_3.setObjectName("l1_3")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout(self.l1_3)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.Exit_3 = QtWidgets.QPushButton(self.l1_3)
        self.Exit_3.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/external-link.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Exit_3.setIcon(icon)
        self.Exit_3.setObjectName("Exit_3")
        self.horizontalLayout_37.addWidget(self.Exit_3)
        self.AI_3 = QtWidgets.QPushButton(self.l1_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AI_3.sizePolicy().hasHeightForWidth())
        self.AI_3.setSizePolicy(sizePolicy)
        self.AI_3.setFocusPolicy(QtCore.Qt.NoFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/cpu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AI_3.setIcon(icon1)
        self.AI_3.setObjectName("AI_3")
        self.horizontalLayout_37.addWidget(self.AI_3)
        self.horizontalLayout_36.addWidget(self.l1_3, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_13.addWidget(self.last_frame_3, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_12.addWidget(self.SliderMenu_3)
        self.horizontalLayout.addWidget(self.slideMenu_container)
        self.MainBody = QtWidgets.QFrame(self.centralwidget)
        self.MainBody.setStyleSheet("border:none;\n"
"")
        self.MainBody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainBody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainBody.setObjectName("MainBody")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.MainBody)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.HeaderFrame_3 = QtWidgets.QFrame(self.MainBody)
        self.HeaderFrame_3.setStyleSheet("")
        self.HeaderFrame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HeaderFrame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HeaderFrame_3.setObjectName("HeaderFrame_3")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.HeaderFrame_3)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.scarch_frame_3 = QtWidgets.QFrame(self.HeaderFrame_3)
        self.scarch_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scarch_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scarch_frame_3.setLineWidth(0)
        self.scarch_frame_3.setObjectName("scarch_frame_3")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.scarch_frame_3)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.Slide_btn_3 = QtWidgets.QPushButton(self.scarch_frame_3)
        self.Slide_btn_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Slide_btn_3.setStyleSheet("QPushButton#Slide_btn_3{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(12, 12, 12);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#Slide_btn_3:hover{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(52, 65, 71);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#Slide_btn_3:pressed{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(83, 83, 83);\n"
"    border-radius:5px;\n"
"}")
        self.Slide_btn_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Slide_btn_3.setIcon(icon2)
        self.Slide_btn_3.setObjectName("Slide_btn_3")
        self.horizontalLayout_27.addWidget(self.Slide_btn_3)
        self.frame_3 = QtWidgets.QFrame(self.scarch_frame_3)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_27.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.scarch_frame_3)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_27.addWidget(self.frame_2)
        self.horizontalLayout_26.addWidget(self.scarch_frame_3)
        self.other_frame_3 = QtWidgets.QFrame(self.HeaderFrame_3)
        self.other_frame_3.setMaximumSize(QtCore.QSize(400, 16777215))
        self.other_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.other_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.other_frame_3.setObjectName("other_frame_3")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.other_frame_3)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.lineEdit = QtWidgets.QLineEdit(self.other_frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(46, 50, 60);\n"
"border-bottom:2px solid gba(46,81,101,200);\n"
"color: rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_28.addWidget(self.lineEdit)
        self.txt_voice = QtWidgets.QPushButton(self.other_frame_3)
        self.txt_voice.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txt_voice.setFocusPolicy(QtCore.Qt.NoFocus)
        self.txt_voice.setStyleSheet("QPushButton#txt_voice\n"
"{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(12, 12, 12);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QPushButton#txt_voice:hover{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(52, 65, 71);\n"
"\n"
"}\n"
"QPushButton#txt_voice:pressed{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(83, 83, 83);\n"
"\n"
"}")
        self.txt_voice.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/mic.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.txt_voice.setIcon(icon3)
        self.txt_voice.setObjectName("txt_voice")
        self.horizontalLayout_28.addWidget(self.txt_voice)
        self.horizontalLayout_26.addWidget(self.other_frame_3)
        self.Empty_3 = QtWidgets.QFrame(self.HeaderFrame_3)
        self.Empty_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Empty_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Empty_3.setObjectName("Empty_3")
        self.horizontalLayout_26.addWidget(self.Empty_3)
        self.frame_15 = QtWidgets.QFrame(self.HeaderFrame_3)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.frame_4 = QtWidgets.QFrame(self.frame_15)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.run_btn = QtWidgets.QPushButton(self.frame_4)
        self.run_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.run_btn.setStyleSheet("QPushButton#run_btn\n"
"{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(12, 12, 12);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#run_btn:hover{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(52, 65, 71);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#run_btn:pressed{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(83, 83, 83);\n"
"    border-radius:5px;\n"
"}")
        self.run_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.run_btn.setIcon(icon4)
        self.run_btn.setObjectName("run_btn")
        self.horizontalLayout_2.addWidget(self.run_btn)
        self.horizontalLayout_29.addWidget(self.frame_4)
        self.voice_btn = QtWidgets.QPushButton(self.frame_15)
        self.voice_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.voice_btn.setStyleSheet("QPushButton#voice_btn\n"
"{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(12, 12, 12);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#voice_btn:hover{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(52, 65, 71);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#voice_btn:pressed{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(83, 83, 83);\n"
"    border-radius:5px;\n"
"}")
        self.voice_btn.setText("")
        self.voice_btn.setIcon(icon3)
        self.voice_btn.setObjectName("voice_btn")
        self.horizontalLayout_29.addWidget(self.voice_btn)
        self.horizontalLayout_26.addWidget(self.frame_15)
        self.verticalLayout_11.addWidget(self.HeaderFrame_3)
        self.MainBody_4 = QtWidgets.QFrame(self.MainBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainBody_4.sizePolicy().hasHeightForWidth())
        self.MainBody_4.setSizePolicy(sizePolicy)
        self.MainBody_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainBody_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainBody_4.setObjectName("MainBody_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.MainBody_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.OutPut_tot = QtWidgets.QFrame(self.MainBody_4)
        self.OutPut_tot.setMaximumSize(QtCore.QSize(16777215, 0))
        self.OutPut_tot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OutPut_tot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OutPut_tot.setObjectName("OutPut_tot")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.OutPut_tot)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Output_frame = QtWidgets.QFrame(self.OutPut_tot)
        self.Output_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Output_frame.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.Output_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Output_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Output_frame.setObjectName("Output_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Output_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.Output_frame)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.close = QtWidgets.QPushButton(self.Output_frame)
        self.close.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.close.setStyleSheet("QPushButton#close{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(12, 12, 12);\n"
"    color: rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#close:hover{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(52, 65, 71);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#close:pressed{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(83, 83, 83);\n"
"    border-radius:5px;\n"
"}")
        self.close.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close.setIcon(icon5)
        self.close.setObjectName("close")
        self.horizontalLayout_3.addWidget(self.close, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.Output_frame)
        self.Output = QtWidgets.QTextEdit(self.OutPut_tot)
        self.Output.setMaximumSize(QtCore.QSize(16777215, 150))
        self.Output.setStyleSheet("background-color: rgb(53, 56, 70);\n"
"background-color: rgb(12, 13, 16);")
        self.Output.setObjectName("Output")
        self.verticalLayout.addWidget(self.Output)
        self.gridLayout_5.addWidget(self.OutPut_tot, 1, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.MainBody_4)
        self.textEdit.setAutoFillBackground(True)
        self.textEdit.setStyleSheet("\n"
"background-color: rgb(52, 55, 68);")
        self.textEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_5.addWidget(self.textEdit, 0, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.MainBody_4)
        self.horizontalLayout.addWidget(self.MainBody)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 24))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actioncopy = QtWidgets.QAction(MainWindow)
        self.actioncopy.setObjectName("actioncopy")
        self.actionpast = QtWidgets.QAction(MainWindow)
        self.actionpast.setObjectName("actionpast")
        self.actionselect_all = QtWidgets.QAction(MainWindow)
        self.actionselect_all.setObjectName("actionselect_all")
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionnew = QtWidgets.QAction(MainWindow)
        self.actionnew.setObjectName("actionnew")
        self.actionrecent = QtWidgets.QAction(MainWindow)
        self.actionrecent.setObjectName("actionrecent")
        self.actionvoice_to_txt = QtWidgets.QAction(MainWindow)
        self.actionvoice_to_txt.setObjectName("actionvoice_to_txt")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPast = QtWidgets.QAction(MainWindow)
        self.actionPast.setObjectName("actionPast")
        self.actionSelete_All = QtWidgets.QAction(MainWindow)
        self.actionSelete_All.setObjectName("actionSelete_All")
        self.actionChanges = QtWidgets.QAction(MainWindow)
        self.actionChanges.setObjectName("actionChanges")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionrun = QtWidgets.QAction(MainWindow)
        self.actionrun.setObjectName("actionrun")
        self.actioncheck = QtWidgets.QAction(MainWindow)
        self.actioncheck.setObjectName("actioncheck")
        self.actionHow_To_Use = QtWidgets.QAction(MainWindow)
        self.actionHow_To_Use.setObjectName("actionHow_To_Use")
        self.actionKnow = QtWidgets.QAction(MainWindow)
        self.actionKnow.setObjectName("actionKnow")
        self.actioncut = QtWidgets.QAction(MainWindow)
        self.actioncut.setObjectName("actioncut")
        self.actionundo = QtWidgets.QAction(MainWindow)
        self.actionundo.setObjectName("actionundo")
        self.actionredo = QtWidgets.QAction(MainWindow)
        self.actionredo.setObjectName("actionredo")
        self.menufile.addAction(self.actionopen)
        self.menufile.addAction(self.actionnew)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionrecent)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionvoice_to_txt)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionsave)
        self.menufile.addAction(self.actionSave_As)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionredo)
        self.menuEdit.addAction(self.actionundo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actioncut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPast)
        self.menuEdit.addAction(self.actionSelete_All)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionChanges)
        self.menuEdit.addAction(self.actionSettings)
        self.menuRun.addAction(self.actionrun)
        self.menuRun.addAction(self.actioncheck)
        self.menuHelp.addAction(self.actionHow_To_Use)
        self.menuHelp.addAction(self.actionKnow)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.Main_toolBox_3.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_13.setText(_translate("MainWindow", "Welcome"))
        self.label_14.setText(_translate("MainWindow", "gui"))
        self.Main_toolBox_3.setItemText(self.Main_toolBox_3.indexOf(self.Home_3), _translate("MainWindow", "Home"))
        self.Btn_class_3.setText(_translate("MainWindow", "Class"))
        self.Btn_meet_3.setText(_translate("MainWindow", "Meet"))
        self.Btn_test_3.setText(_translate("MainWindow", "Test"))
        self.Btn_trans_3.setText(_translate("MainWindow", "Transulator"))
        self.Btn_players_3.setText(_translate("MainWindow", "Players"))
        self.Btn_Board_3.setText(_translate("MainWindow", "White Board"))
        self.Btn_notepad_3.setText(_translate("MainWindow", "Note Pad"))
        self.Btn_timeTable_3.setText(_translate("MainWindow", "Time Table"))
        self.Btn_SocialMidea_3.setText(_translate("MainWindow", "Social Midea"))
        self.Btn_Others_3.setText(_translate("MainWindow", "Others"))
        self.Main_toolBox_3.setItemText(self.Main_toolBox_3.indexOf(self.Class_3), _translate("MainWindow", "Class"))
        self.Main_toolBox_3.setItemText(self.Main_toolBox_3.indexOf(self.page_7), _translate("MainWindow", "Settings"))
        self.Exit_3.setText(_translate("MainWindow", "Exit"))
        self.AI_3.setText(_translate("MainWindow", "AI"))
        self.label.setText(_translate("MainWindow", "OutPut"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.actioncopy.setText(_translate("MainWindow", "copy"))
        self.actionpast.setText(_translate("MainWindow", "past"))
        self.actionselect_all.setText(_translate("MainWindow", "select all"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionnew.setText(_translate("MainWindow", "new"))
        self.actionrecent.setText(_translate("MainWindow", "recent"))
        self.actionvoice_to_txt.setText(_translate("MainWindow", "voice to txt"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionPast.setText(_translate("MainWindow", "Past"))
        self.actionSelete_All.setText(_translate("MainWindow", "Selete All"))
        self.actionChanges.setText(_translate("MainWindow", "Changes"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionrun.setText(_translate("MainWindow", "run"))
        self.actioncheck.setText(_translate("MainWindow", "check"))
        self.actionHow_To_Use.setText(_translate("MainWindow", "How To Use"))
        self.actionKnow.setText(_translate("MainWindow", "Know"))
        self.actioncut.setText(_translate("MainWindow", "cut"))
        self.actionundo.setText(_translate("MainWindow", "undo"))
        self.actionredo.setText(_translate("MainWindow", "redo"))
from py_image_ui import icon_rc
